# Generated by Django 5.2.14 on 2026-05-17 13:57

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sovtimer", "0001_initialize"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sovereigntystructure", name="structure_type_id"
        ),
    ]
