# Generated by Django 3.1.3 on 2020-11-14 07:20

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sovtimer", "0004_auto_20201113_1856"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aasovtimercampaigns",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("ihub_defense", "IHub Defense"),
                    ("tcu_defense", "TCU Defense"),
                ],
                max_length=12,
            ),
        ),
    ]
