# Generated by Django 4.2.28 on 2026-02-25 01:11

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0012_alter_constellation_region"),
        ("sovtimer", "0010_alter_campaign_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alliance",
            fields=[
                (
                    "alliance_id",
                    models.PositiveBigIntegerField(
                        db_index=True, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Alliance",
                "verbose_name_plural": "Alliances",
                "default_permissions": (),
            },
        ),
        migrations.AlterField(
            model_name="campaign",
            name="event_type",
            field=models.CharField(
                choices=[("sovhub", "Sov Hub defense")], default="sovhub", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="sovereigntystructure",
            name="solar_system",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sov_structure_solar_system",
                to="eve_sde.solarsystem",
            ),
        ),
        migrations.AlterField(
            model_name="sovereigntystructure",
            name="alliance",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sov_structure_alliance",
                to="sovtimer.alliance",
            ),
        ),
    ]
